### ISSUE TITLE
The terminal does not reliably start

### ISSUE THREAD

**Issue by zebulasampedro** [SandstoneHPC/sandstonehpc-project#52]
After moving to the `UniqueTermManager` and porting the terminal socket setup code to a controller, the web terminal does not reliably start up.

The likely cause of this is that the low per-user terminal limit set on the manager (3) is being hit quickly as every navigation event to the web terminal app builds a new terminal.

**Comment by saurabhsood91** [comment]
removing the `max_terminals=3` parameter fixes it. Not sure if that is desirable though
